### ISSUE TITLE
Next Track and Change Track failed

### ISSUE THREAD

**Issue by alifgiant** [fishuke/ytmparty#1]
Hi, thanks for the awesome extension.

But while trying this out, I face problem. Every time I click on next track button, what happened on my partner device is that the song got repeated instead of changed.

Also every time I click play on another song, nothing happened to my partner device.

**Comment by fishuke** [comment]
Thanks for opening issue and sorry for being so late. I will have better look on this problem.

**Comment by fishuke** [comment]
Fixed with new version.

**Comment by alifgiant** [comment]
wow.. how can I try the new version?

**Comment by fishuke** [comment]
Its currently wating for review. Once its published you will see...

**Comment by fishuke** [comment]
@alifgiant here you go https://chrome.google.com/webstore/detail/youtube-music-party/cdmmbghbolflmmfecknfkjcflnadaocg
