### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by plutonium-239** [fishuke/ytmparty#13]
Hey... I tried to run this extension... just gives me this screen: 
![image](https://user-images.githubusercontent.com/29684689/174437330-5cc7b5e7-4654-4c44-84ee-afd26fa8cfca.png)

I cant seem to either figure out how to get it working at the other end or it doesn't work like its supposed to

**Comment by fishuke** [comment]
You are in party now just send this party code to your friend and join the same room.
Then go to music.youtube.com and play something.

**Comment by plutonium-239** [comment]
Yes, that is not working.
The other person can join and sees this same screen and on playing nothing happens

**Comment by fishuke** [comment]
i see let me debug what is wrong...

**Comment by fishuke** [comment]
You need to reload the page after joining a room i guess, it seems working on my side...

**Comment by fishuke** [comment]
Steps to follow: 
Install the extension.
Leave the room if you are in.
Refresh youtube music and play a music.
Join a room.
It will be working.

**Comment by plutonium-239** [comment]
Not working for me :/
I refreshed the page without party and then joined but still no
I tried reinstalling it too
Is it supposed to display something (like name/album art/controls etc)?

**Comment by fishuke** [comment]
Please join discord then i can investigate the problem: https://discord.gg/vY9DfbB8mG
